#!/bin/bash
# Mark code as reviewed
# Usage: ./scripts/mark-reviewed.sh [reviewer_name] [status]

REVIEWER=${1:-"$(whoami)"}
STATUS=${2:-"passed"}
DATE=$(date +%Y-%m-%d)

cat > .code-review-status << EOL
# Code Review Status
# This file is auto-generated by mark-reviewed.sh

last_reviewed: $DATE
reviewer: $REVIEWER
status: $STATUS
commit: $(git rev-parse HEAD 2>/dev/null || echo "unknown")
EOL

echo "✓ Code marked as reviewed"
echo "  Date: $DATE"
echo "  Reviewer: $REVIEWER"
echo "  Status: $STATUS"
